### PR TITLE
Meower beta 5 revision 4

### PR DESCRIPTION
**Pull request by wgyt**
* makes /status of api including a key of scratchDeprecated with a value
  of true show a deprecated credits scene
* updates build number

### CODE REVIEW

**Comment by wgyt** [comment]
@MikeDev101 needs to allow `scratch-beta-5-r4` server side before this can be merged

**Comment by MikeDev101** [comment]
> Sandboxed mode detected, performance will suffer because of the extension being sandboxed.
@wgyt you imported CL Turbo wrong

**Comment by wgyt** [comment]
@MikeDev101 can you fix it?

**Comment by MikeDev101** [comment]
> @MikeDev101 can you fix it?

Fixable, but just annoying. FYI for future fixes or updates: just extract the contents of the source code's SB3 files into the dist/assets folder.

**Pull request merged**
